language: node_js
sudo: false
dist: trusty

node_js:
  - '7.10.0'
addons:
#  firefox: "38.0"
  apt:
    sources:
      # needed to install g++ that is used by npms's native modules
      - ubuntu-toolchain-r-test
    packages:
      # needed to install g++ that is used by npms's native modules
      - g++-4.8

branches:
  only:
  - master

cache:
  yarn: true
  directories:
     - ./node_modules

matrix:
  fast_finish: true
  allow_failures:
    - env: "CI_MODE=saucelabs_optional"
    - env: "CI_MODE=browserstack_optional"
    - env: "CI_MODE=aio_e2e"